# MYSQL DATABASE DOCKER IMAGE
FROM mysql:8.0.17
# DEFINED LENGUAGE OS
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
# MYSQL DEFINITION
ENV MYSQL_ROOT_PASSWORD '1234567890'
ENV MYSQL_DATABASE ecommerce_db
